重要基础课
SCU-CS-Runner/SurviveSCUManual pull request #27
Opened 2022-08-13 14:18 UTC by WhileBug

一些重要基础课程的更新（还没完善，各位佬多写写），我主要是像弄一个针对AI和System分别的完整清晰的学习路径

2022-08-13 14:23 UTC, IzaiahSun reviewed
Line 2，建议把狗屎改个表述，过于情绪化了。
Line 5和Line 16同理

2022-08-13 14:28 UTC, MrZilinXiao commented on 1-save-self/4-important-basics.md
> +川大的CS相关基础课程宛如🐕💩一样的质量相信各位已经见识过了，下面WhileBug将逐一介绍一些重要的基础课程，以及如何在你川糟糕的基础课程条件下自救。
好暴躁的Bug哥，好喜欢

2022-08-13 14:28 UTC, MrZilinXiao commented on 1-save-self/4-important-basics.md
> +System Research的进阶课程包含编译原理、分布式系统、操作系统、计算机网络和数据库等相关课程。然而你川在这方面的课程质量尤其焚书坑儒。先不说数据库只讲SQL语言而不讲实现原理这种傻逼操作，分布式系统这种重要的课程甚至完全没开。
好暴躁的Bug哥，好爱
（CS的数据库还是讲了原理的

2022-08-13 14:28 UTC, MrZilinXiao commented on 1-save-self/4-important-basics.md
> +[MIT-分布式系统](https://www.bilibili.com/video/BV1CU4y1P7PE?spm_id_from=333.337.search-card.all.click&vd_source=83d0dd327837606efeb7ba762911a4f4)
建议移除所有URL的reference parameter；别误导叔叔家的统计啦

2022-08-13 14:29 UTC, IzaiahSun approved these changes

2022-08-13 14:32 UTC, TomAPU commented on 1-save-self/4-important-basics.md
> +川大的CS相关基础课程宛如🐕💩一样的质量相信各位已经见识过了，下面WhileBug将逐一介绍一些重要的基础课程，以及如何在你川糟糕的基础课程条件下自救。
爱了爱了~

2022-08-13 16:44 UTC, CharesFang commented on 1-save-self/4-important-basics.md
> +[MIT-分布式系统](https://www.bilibili.com/video/BV1CU4y1P7PE?spm_id_from=333.337.search-card.all.click&vd_source=83d0dd327837606efeb7ba762911a4f4)
> 

好骂

2022-08-13 16:45 UTC, CharesFang commented on 1-save-self/4-important-basics.md
> +[MIT-分布式系统](https://www.bilibili.com/video/BV1CU4y1P7PE?spm_id_from=333.337.search-card.all.click&vd_source=83d0dd327837606efeb7ba762911a4f4)
> 建议移除所有URL的reference parameter；别误导叔叔家的统计啦

好骂

2022-08-16 07:32 UTC, IzaiahSun reviewed
我建议可以放点图，关于PhD的常见误区，我要么直接在你的分支山改吧

2022-08-16 12:40 UTC, CharesFang requested changes
Block PR due to incomplete subsections

2022-08-16 12:40 UTC, CharesFang commented on 1-save-self/4-important-basics.md
> +## AI进阶篇-如何进入AI的世界
WhileBug把这一章写完再PR不。

2022-08-16 12:40 UTC, CharesFang commented on 1-save-self/4-important-basics.md
> +## CS基础篇-小白如何建立起对CS的整体了解以及相关基础课程
还有这一个section，你先写完直接在你的分支上commit我最后一起merge

2022-08-16 12:45 UTC, merged